---
# handlers file for ui_and_comment
- name: reload reddit-ui
  systemd: 
    name: reddit-ui
    state: restarted 
    daemon_reload: true

- name: reload reddit-comment
  systemd: 
    name: reddit-comment
    state: restarted 
    daemon_reload: true