---
- hosts: ui
  become: true
  roles: 
  - import_role:
    name: ui_and_comment
    vars: 
    - components: [ui]
  pre_tasks:
  - name: clone repo
    import_tasks: install_repo.yaml

- hosts: comment
  become: true
  roles: 
  - import_role:
    name: ui_and_comment
    vars: 
    - components: [comment]
  pre_tasks:
  - name: clone repo
    import_tasks: install_repo.yaml