---
# tasks file for ui_and_comment
- name: install bundler
  apt:
    name: bundler
    state: present
    update_cache: true

- name: install components dependencies
  bundler:
    state: present
    gemfile: /opt/reddit/{{ item }}/Gemfile
  loop: "{{ components }}"

- name: add component config
  template:
    src: "{{ item }}_config.j2"
    dest: /opt/reddit/{{ item }}/{{ item }}_config
  notify: reload reddit-{{ item }}
  loop: "{{ components }}"

- name: add component services
  template:
    src: reddit-{{ item }}.service.j2
    dest: /etc/systemd/system/reddit-{{ item }}.service
  notify: reload reddit-{{ item }}
  loop: "{{ components }}"

- name: enable and start components
  systemd:
    state: started
    name: reddit-{{ item }}
    enabled: true
    daemon_reload: true
  loop: "{{ components }}"


